name: omulimisa2
description: a new flutter project
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 25.1.0+34

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  #  flutx:
  #    path: ./flutx14

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  loading_animation_widget: ^1.2.0+4
  loader_overlay: ^2.2.0
  font_awesome_flutter: ^10.5.0
  introduction_screen: ^3.1.9
  flutter_onboard: ^2.0.0
  get: ^4.6.5
  shared_preferences: ^2.2.0
  dartz: ^0.10.1
  json_annotation: ^4.8.1
  logger: ^1.4.0
  html: ^0.15.4
  video_player: ^2.7.0
  #flutter_file_downloader: ^1.1.2
  url_launcher: ^6.1.12
  image_picker: ^1.0.1
  dio: ^5.3.0
  internet_connection_checker: ^1.0.0+1
  shimmer: ^2.0.0
  intl: ^0.17.0
  google_maps_flutter: ^2.3.1
  geolocator: ^9.0.2

  flutter_form_builder: 9.0.0
  form_builder_validators: 9.0.0
  flutter_feather_icons: ^2.0.0+1
  material_design_icons_flutter: ^7.0.7296
  sqflite: ^2.2.8+4
  google_fonts: ^5.1.0
  flutx: ^0.2.0-rc.2
  fluttertoast: ^8.0.9
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  dropdown_button2: ^2.3.6
  carousel_slider: ^4.2.1
  audio_session: ^0.1.16
  flutter_sound: ^9.2.13
  permission_handler: ^10.4.3
  onesignal_flutter: 3.5.0
  path_provider: ^2.1.0
  flutter_html: ^3.0.0-beta.2
  easy_image_viewer: ^1.2.1
  change_app_package_name: ^1.1.0
  flutter_pdfview: ^1.3.1
  http: ^1.1.0
  youtube_player_flutter: ^8.1.2
  flutter_cached_pdfview: ^0.4.2
  youtube_player_iframe: ^4.0.4
  flutter_polyline_points: ^2.0.0
  #flutter_inappwebview: ^5.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

dependency_overrides:
  intl: any
  http: any
  google_fonts: any
  provider: any
  nested: any

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/rain.png
    - assets/images/user.jpg
    - assets/images/wav.png